# https://v1-9.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
# https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/hello-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080